/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartProjectRouteImport } from './routes/start-project'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWebsitesRouteImport } from './routes/services.websites'
import { Route as ServicesSaasPlatformsRouteImport } from './routes/services.saas-platforms'
import { Route as ServicesMobileAppsRouteImport } from './routes/services.mobile-apps'
import { Route as ServicesCustomSoftwareRouteImport } from './routes/services.custom-software'
import { Route as ServicesAiAutomationRouteImport } from './routes/services.ai-automation'
import { Route as ServicesAiAgentsRouteImport } from './routes/services.ai-agents'

const StartProjectRoute = StartProjectRouteImport.update({
  id: '/start-project',
  path: '/start-project',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebsitesRoute = ServicesWebsitesRouteImport.update({
  id: '/services/websites',
  path: '/services/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSaasPlatformsRoute = ServicesSaasPlatformsRouteImport.update({
  id: '/services/saas-platforms',
  path: '/services/saas-platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMobileAppsRoute = ServicesMobileAppsRouteImport.update({
  id: '/services/mobile-apps',
  path: '/services/mobile-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCustomSoftwareRoute = ServicesCustomSoftwareRouteImport.update({
  id: '/services/custom-software',
  path: '/services/custom-software',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiAutomationRoute = ServicesAiAutomationRouteImport.update({
  id: '/services/ai-automation',
  path: '/services/ai-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiAgentsRoute = ServicesAiAgentsRouteImport.update({
  id: '/services/ai-agents',
  path: '/services/ai-agents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-project': typeof StartProjectRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/ai-automation': typeof ServicesAiAutomationRoute
  '/services/custom-software': typeof ServicesCustomSoftwareRoute
  '/services/mobile-apps': typeof ServicesMobileAppsRoute
  '/services/saas-platforms': typeof ServicesSaasPlatformsRoute
  '/services/websites': typeof ServicesWebsitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-project': typeof StartProjectRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/ai-automation': typeof ServicesAiAutomationRoute
  '/services/custom-software': typeof ServicesCustomSoftwareRoute
  '/services/mobile-apps': typeof ServicesMobileAppsRoute
  '/services/saas-platforms': typeof ServicesSaasPlatformsRoute
  '/services/websites': typeof ServicesWebsitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-project': typeof StartProjectRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/ai-automation': typeof ServicesAiAutomationRoute
  '/services/custom-software': typeof ServicesCustomSoftwareRoute
  '/services/mobile-apps': typeof ServicesMobileAppsRoute
  '/services/saas-platforms': typeof ServicesSaasPlatformsRoute
  '/services/websites': typeof ServicesWebsitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/start-project'
    | '/services/ai-agents'
    | '/services/ai-automation'
    | '/services/custom-software'
    | '/services/mobile-apps'
    | '/services/saas-platforms'
    | '/services/websites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/start-project'
    | '/services/ai-agents'
    | '/services/ai-automation'
    | '/services/custom-software'
    | '/services/mobile-apps'
    | '/services/saas-platforms'
    | '/services/websites'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/start-project'
    | '/services/ai-agents'
    | '/services/ai-automation'
    | '/services/custom-software'
    | '/services/mobile-apps'
    | '/services/saas-platforms'
    | '/services/websites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartProjectRoute: typeof StartProjectRoute
  ServicesAiAgentsRoute: typeof ServicesAiAgentsRoute
  ServicesAiAutomationRoute: typeof ServicesAiAutomationRoute
  ServicesCustomSoftwareRoute: typeof ServicesCustomSoftwareRoute
  ServicesMobileAppsRoute: typeof ServicesMobileAppsRoute
  ServicesSaasPlatformsRoute: typeof ServicesSaasPlatformsRoute
  ServicesWebsitesRoute: typeof ServicesWebsitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start-project': {
      id: '/start-project'
      path: '/start-project'
      fullPath: '/start-project'
      preLoaderRoute: typeof StartProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/websites': {
      id: '/services/websites'
      path: '/services/websites'
      fullPath: '/services/websites'
      preLoaderRoute: typeof ServicesWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/saas-platforms': {
      id: '/services/saas-platforms'
      path: '/services/saas-platforms'
      fullPath: '/services/saas-platforms'
      preLoaderRoute: typeof ServicesSaasPlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mobile-apps': {
      id: '/services/mobile-apps'
      path: '/services/mobile-apps'
      fullPath: '/services/mobile-apps'
      preLoaderRoute: typeof ServicesMobileAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-software': {
      id: '/services/custom-software'
      path: '/services/custom-software'
      fullPath: '/services/custom-software'
      preLoaderRoute: typeof ServicesCustomSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-automation': {
      id: '/services/ai-automation'
      path: '/services/ai-automation'
      fullPath: '/services/ai-automation'
      preLoaderRoute: typeof ServicesAiAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-agents': {
      id: '/services/ai-agents'
      path: '/services/ai-agents'
      fullPath: '/services/ai-agents'
      preLoaderRoute: typeof ServicesAiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartProjectRoute: StartProjectRoute,
  ServicesAiAgentsRoute: ServicesAiAgentsRoute,
  ServicesAiAutomationRoute: ServicesAiAutomationRoute,
  ServicesCustomSoftwareRoute: ServicesCustomSoftwareRoute,
  ServicesMobileAppsRoute: ServicesMobileAppsRoute,
  ServicesSaasPlatformsRoute: ServicesSaasPlatformsRoute,
  ServicesWebsitesRoute: ServicesWebsitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
